/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as LoginImport } from './routes/login';
import { Route as BaselayoutImport } from './routes/_baselayout';
import { Route as SlugImport } from './routes/$slug';
import { Route as IndexImport } from './routes/index';
import { Route as SlugIndexImport } from './routes/$slug/index';
import { Route as BaselayoutVideoIndexImport } from './routes/_baselayout/video/index';
import { Route as BaselayoutSettingsIndexImport } from './routes/_baselayout/settings/index';
import { Route as BaselayoutHelpIndexImport } from './routes/_baselayout/help/index';
import { Route as BaselayoutContactsIndexImport } from './routes/_baselayout/contacts/index';
import { Route as SlugVideoIndexImport } from './routes/$slug/video/index';
import { Route as SlugSettingsIndexImport } from './routes/$slug/settings/index';
import { Route as SlugHelpIndexImport } from './routes/$slug/help/index';
import { Route as SlugContactsIndexImport } from './routes/$slug/contacts/index';
import { Route as BaselayoutFolderFolderIndexImport } from './routes/_baselayout/folder/$folder/index';
import { Route as R1219AdminLoginIndexImport } from './routes/1219/admin/login/index';
import { Route as R1219AdminDomainIndexImport } from './routes/1219/admin/domain/index';
import { Route as SlugFolderFolderIndexImport } from './routes/$slug/folder.$folder/index';
import { Route as R1219AdminDomainAddIndexImport } from './routes/1219/admin/domain/add/index';
import { Route as R1219AdminDomainEditDomainIndexImport } from './routes/1219/admin/domain/edit.$domain/index';

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const BaselayoutRoute = BaselayoutImport.update({
  id: '/_baselayout',
  getParentRoute: () => rootRoute,
} as any);

const SlugRoute = SlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const SlugIndexRoute = SlugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any);

const BaselayoutVideoIndexRoute = BaselayoutVideoIndexImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => BaselayoutRoute,
} as any);

const BaselayoutSettingsIndexRoute = BaselayoutSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => BaselayoutRoute,
} as any);

const BaselayoutHelpIndexRoute = BaselayoutHelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => BaselayoutRoute,
} as any);

const BaselayoutContactsIndexRoute = BaselayoutContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => BaselayoutRoute,
} as any);

const SlugVideoIndexRoute = SlugVideoIndexImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => SlugRoute,
} as any);

const SlugSettingsIndexRoute = SlugSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => SlugRoute,
} as any);

const SlugHelpIndexRoute = SlugHelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => SlugRoute,
} as any);

const SlugContactsIndexRoute = SlugContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => SlugRoute,
} as any);

const BaselayoutFolderFolderIndexRoute = BaselayoutFolderFolderIndexImport.update({
  id: '/folder/$folder/',
  path: '/folder/$folder/',
  getParentRoute: () => BaselayoutRoute,
} as any);

const R1219AdminLoginIndexRoute = R1219AdminLoginIndexImport.update({
  id: '/1219/admin/login/',
  path: '/1219/admin/login/',
  getParentRoute: () => rootRoute,
} as any);

const R1219AdminDomainIndexRoute = R1219AdminDomainIndexImport.update({
  id: '/1219/admin/domain/',
  path: '/1219/admin/domain/',
  getParentRoute: () => rootRoute,
} as any);

const SlugFolderFolderIndexRoute = SlugFolderFolderIndexImport.update({
  id: '/folder/$folder/',
  path: '/folder/$folder/',
  getParentRoute: () => SlugRoute,
} as any);

const R1219AdminDomainAddIndexRoute = R1219AdminDomainAddIndexImport.update({
  id: '/1219/admin/domain/add/',
  path: '/1219/admin/domain/add/',
  getParentRoute: () => rootRoute,
} as any);

const R1219AdminDomainEditDomainIndexRoute = R1219AdminDomainEditDomainIndexImport.update({
  id: '/1219/admin/domain/edit/$domain/',
  path: '/1219/admin/domain/edit/$domain/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/$slug': {
      id: '/$slug';
      path: '/$slug';
      fullPath: '/$slug';
      preLoaderRoute: typeof SlugImport;
      parentRoute: typeof rootRoute;
    };
    '/_baselayout': {
      id: '/_baselayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof BaselayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/$slug/': {
      id: '/$slug/';
      path: '/';
      fullPath: '/$slug/';
      preLoaderRoute: typeof SlugIndexImport;
      parentRoute: typeof SlugImport;
    };
    '/$slug/contacts/': {
      id: '/$slug/contacts/';
      path: '/contacts';
      fullPath: '/$slug/contacts';
      preLoaderRoute: typeof SlugContactsIndexImport;
      parentRoute: typeof SlugImport;
    };
    '/$slug/help/': {
      id: '/$slug/help/';
      path: '/help';
      fullPath: '/$slug/help';
      preLoaderRoute: typeof SlugHelpIndexImport;
      parentRoute: typeof SlugImport;
    };
    '/$slug/settings/': {
      id: '/$slug/settings/';
      path: '/settings';
      fullPath: '/$slug/settings';
      preLoaderRoute: typeof SlugSettingsIndexImport;
      parentRoute: typeof SlugImport;
    };
    '/$slug/video/': {
      id: '/$slug/video/';
      path: '/video';
      fullPath: '/$slug/video';
      preLoaderRoute: typeof SlugVideoIndexImport;
      parentRoute: typeof SlugImport;
    };
    '/_baselayout/contacts/': {
      id: '/_baselayout/contacts/';
      path: '/contacts';
      fullPath: '/contacts';
      preLoaderRoute: typeof BaselayoutContactsIndexImport;
      parentRoute: typeof BaselayoutImport;
    };
    '/_baselayout/help/': {
      id: '/_baselayout/help/';
      path: '/help';
      fullPath: '/help';
      preLoaderRoute: typeof BaselayoutHelpIndexImport;
      parentRoute: typeof BaselayoutImport;
    };
    '/_baselayout/settings/': {
      id: '/_baselayout/settings/';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof BaselayoutSettingsIndexImport;
      parentRoute: typeof BaselayoutImport;
    };
    '/_baselayout/video/': {
      id: '/_baselayout/video/';
      path: '/video';
      fullPath: '/video';
      preLoaderRoute: typeof BaselayoutVideoIndexImport;
      parentRoute: typeof BaselayoutImport;
    };
    '/$slug/folder/$folder/': {
      id: '/$slug/folder/$folder/';
      path: '/folder/$folder';
      fullPath: '/$slug/folder/$folder';
      preLoaderRoute: typeof SlugFolderFolderIndexImport;
      parentRoute: typeof SlugImport;
    };
    '/1219/admin/domain/': {
      id: '/1219/admin/domain/';
      path: '/1219/admin/domain';
      fullPath: '/1219/admin/domain';
      preLoaderRoute: typeof R1219AdminDomainIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/1219/admin/login/': {
      id: '/1219/admin/login/';
      path: '/1219/admin/login';
      fullPath: '/1219/admin/login';
      preLoaderRoute: typeof R1219AdminLoginIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_baselayout/folder/$folder/': {
      id: '/_baselayout/folder/$folder/';
      path: '/folder/$folder';
      fullPath: '/folder/$folder';
      preLoaderRoute: typeof BaselayoutFolderFolderIndexImport;
      parentRoute: typeof BaselayoutImport;
    };
    '/1219/admin/domain/add/': {
      id: '/1219/admin/domain/add/';
      path: '/1219/admin/domain/add';
      fullPath: '/1219/admin/domain/add';
      preLoaderRoute: typeof R1219AdminDomainAddIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/1219/admin/domain/edit/$domain/': {
      id: '/1219/admin/domain/edit/$domain/';
      path: '/1219/admin/domain/edit/$domain';
      fullPath: '/1219/admin/domain/edit/$domain';
      preLoaderRoute: typeof R1219AdminDomainEditDomainIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

interface SlugRouteChildren {
  SlugIndexRoute: typeof SlugIndexRoute;
  SlugContactsIndexRoute: typeof SlugContactsIndexRoute;
  SlugHelpIndexRoute: typeof SlugHelpIndexRoute;
  SlugSettingsIndexRoute: typeof SlugSettingsIndexRoute;
  SlugVideoIndexRoute: typeof SlugVideoIndexRoute;
  SlugFolderFolderIndexRoute: typeof SlugFolderFolderIndexRoute;
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugIndexRoute: SlugIndexRoute,
  SlugContactsIndexRoute: SlugContactsIndexRoute,
  SlugHelpIndexRoute: SlugHelpIndexRoute,
  SlugSettingsIndexRoute: SlugSettingsIndexRoute,
  SlugVideoIndexRoute: SlugVideoIndexRoute,
  SlugFolderFolderIndexRoute: SlugFolderFolderIndexRoute,
};

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren);

interface BaselayoutRouteChildren {
  BaselayoutContactsIndexRoute: typeof BaselayoutContactsIndexRoute;
  BaselayoutHelpIndexRoute: typeof BaselayoutHelpIndexRoute;
  BaselayoutSettingsIndexRoute: typeof BaselayoutSettingsIndexRoute;
  BaselayoutVideoIndexRoute: typeof BaselayoutVideoIndexRoute;
  BaselayoutFolderFolderIndexRoute: typeof BaselayoutFolderFolderIndexRoute;
}

const BaselayoutRouteChildren: BaselayoutRouteChildren = {
  BaselayoutContactsIndexRoute: BaselayoutContactsIndexRoute,
  BaselayoutHelpIndexRoute: BaselayoutHelpIndexRoute,
  BaselayoutSettingsIndexRoute: BaselayoutSettingsIndexRoute,
  BaselayoutVideoIndexRoute: BaselayoutVideoIndexRoute,
  BaselayoutFolderFolderIndexRoute: BaselayoutFolderFolderIndexRoute,
};

const BaselayoutRouteWithChildren = BaselayoutRoute._addFileChildren(BaselayoutRouteChildren);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$slug': typeof SlugRouteWithChildren;
  '': typeof BaselayoutRouteWithChildren;
  '/login': typeof LoginRoute;
  '/$slug/': typeof SlugIndexRoute;
  '/$slug/contacts': typeof SlugContactsIndexRoute;
  '/$slug/help': typeof SlugHelpIndexRoute;
  '/$slug/settings': typeof SlugSettingsIndexRoute;
  '/$slug/video': typeof SlugVideoIndexRoute;
  '/contacts': typeof BaselayoutContactsIndexRoute;
  '/help': typeof BaselayoutHelpIndexRoute;
  '/settings': typeof BaselayoutSettingsIndexRoute;
  '/video': typeof BaselayoutVideoIndexRoute;
  '/$slug/folder/$folder': typeof SlugFolderFolderIndexRoute;
  '/1219/admin/domain': typeof R1219AdminDomainIndexRoute;
  '/1219/admin/login': typeof R1219AdminLoginIndexRoute;
  '/folder/$folder': typeof BaselayoutFolderFolderIndexRoute;
  '/1219/admin/domain/add': typeof R1219AdminDomainAddIndexRoute;
  '/1219/admin/domain/edit/$domain': typeof R1219AdminDomainEditDomainIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '': typeof BaselayoutRouteWithChildren;
  '/login': typeof LoginRoute;
  '/$slug': typeof SlugIndexRoute;
  '/$slug/contacts': typeof SlugContactsIndexRoute;
  '/$slug/help': typeof SlugHelpIndexRoute;
  '/$slug/settings': typeof SlugSettingsIndexRoute;
  '/$slug/video': typeof SlugVideoIndexRoute;
  '/contacts': typeof BaselayoutContactsIndexRoute;
  '/help': typeof BaselayoutHelpIndexRoute;
  '/settings': typeof BaselayoutSettingsIndexRoute;
  '/video': typeof BaselayoutVideoIndexRoute;
  '/$slug/folder/$folder': typeof SlugFolderFolderIndexRoute;
  '/1219/admin/domain': typeof R1219AdminDomainIndexRoute;
  '/1219/admin/login': typeof R1219AdminLoginIndexRoute;
  '/folder/$folder': typeof BaselayoutFolderFolderIndexRoute;
  '/1219/admin/domain/add': typeof R1219AdminDomainAddIndexRoute;
  '/1219/admin/domain/edit/$domain': typeof R1219AdminDomainEditDomainIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/$slug': typeof SlugRouteWithChildren;
  '/_baselayout': typeof BaselayoutRouteWithChildren;
  '/login': typeof LoginRoute;
  '/$slug/': typeof SlugIndexRoute;
  '/$slug/contacts/': typeof SlugContactsIndexRoute;
  '/$slug/help/': typeof SlugHelpIndexRoute;
  '/$slug/settings/': typeof SlugSettingsIndexRoute;
  '/$slug/video/': typeof SlugVideoIndexRoute;
  '/_baselayout/contacts/': typeof BaselayoutContactsIndexRoute;
  '/_baselayout/help/': typeof BaselayoutHelpIndexRoute;
  '/_baselayout/settings/': typeof BaselayoutSettingsIndexRoute;
  '/_baselayout/video/': typeof BaselayoutVideoIndexRoute;
  '/$slug/folder/$folder/': typeof SlugFolderFolderIndexRoute;
  '/1219/admin/domain/': typeof R1219AdminDomainIndexRoute;
  '/1219/admin/login/': typeof R1219AdminLoginIndexRoute;
  '/_baselayout/folder/$folder/': typeof BaselayoutFolderFolderIndexRoute;
  '/1219/admin/domain/add/': typeof R1219AdminDomainAddIndexRoute;
  '/1219/admin/domain/edit/$domain/': typeof R1219AdminDomainEditDomainIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$slug'
    | ''
    | '/login'
    | '/$slug/'
    | '/$slug/contacts'
    | '/$slug/help'
    | '/$slug/settings'
    | '/$slug/video'
    | '/contacts'
    | '/help'
    | '/settings'
    | '/video'
    | '/$slug/folder/$folder'
    | '/1219/admin/domain'
    | '/1219/admin/login'
    | '/folder/$folder'
    | '/1219/admin/domain/add'
    | '/1219/admin/domain/edit/$domain';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | ''
    | '/login'
    | '/$slug'
    | '/$slug/contacts'
    | '/$slug/help'
    | '/$slug/settings'
    | '/$slug/video'
    | '/contacts'
    | '/help'
    | '/settings'
    | '/video'
    | '/$slug/folder/$folder'
    | '/1219/admin/domain'
    | '/1219/admin/login'
    | '/folder/$folder'
    | '/1219/admin/domain/add'
    | '/1219/admin/domain/edit/$domain';
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_baselayout'
    | '/login'
    | '/$slug/'
    | '/$slug/contacts/'
    | '/$slug/help/'
    | '/$slug/settings/'
    | '/$slug/video/'
    | '/_baselayout/contacts/'
    | '/_baselayout/help/'
    | '/_baselayout/settings/'
    | '/_baselayout/video/'
    | '/$slug/folder/$folder/'
    | '/1219/admin/domain/'
    | '/1219/admin/login/'
    | '/_baselayout/folder/$folder/'
    | '/1219/admin/domain/add/'
    | '/1219/admin/domain/edit/$domain/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SlugRoute: typeof SlugRouteWithChildren;
  BaselayoutRoute: typeof BaselayoutRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  R1219AdminDomainIndexRoute: typeof R1219AdminDomainIndexRoute;
  R1219AdminLoginIndexRoute: typeof R1219AdminLoginIndexRoute;
  R1219AdminDomainAddIndexRoute: typeof R1219AdminDomainAddIndexRoute;
  R1219AdminDomainEditDomainIndexRoute: typeof R1219AdminDomainEditDomainIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  BaselayoutRoute: BaselayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  R1219AdminDomainIndexRoute: R1219AdminDomainIndexRoute,
  R1219AdminLoginIndexRoute: R1219AdminLoginIndexRoute,
  R1219AdminDomainAddIndexRoute: R1219AdminDomainAddIndexRoute,
  R1219AdminDomainEditDomainIndexRoute: R1219AdminDomainEditDomainIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$slug",
        "/_baselayout",
        "/login",
        "/1219/admin/domain/",
        "/1219/admin/login/",
        "/1219/admin/domain/add/",
        "/1219/admin/domain/edit/$domain/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$slug": {
      "filePath": "$slug.tsx",
      "children": [
        "/$slug/",
        "/$slug/contacts/",
        "/$slug/help/",
        "/$slug/settings/",
        "/$slug/video/",
        "/$slug/folder/$folder/"
      ]
    },
    "/_baselayout": {
      "filePath": "_baselayout.tsx",
      "children": [
        "/_baselayout/contacts/",
        "/_baselayout/help/",
        "/_baselayout/settings/",
        "/_baselayout/video/",
        "/_baselayout/folder/$folder/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/$slug/": {
      "filePath": "$slug/index.tsx",
      "parent": "/$slug"
    },
    "/$slug/contacts/": {
      "filePath": "$slug/contacts/index.tsx",
      "parent": "/$slug"
    },
    "/$slug/help/": {
      "filePath": "$slug/help/index.tsx",
      "parent": "/$slug"
    },
    "/$slug/settings/": {
      "filePath": "$slug/settings/index.tsx",
      "parent": "/$slug"
    },
    "/$slug/video/": {
      "filePath": "$slug/video/index.tsx",
      "parent": "/$slug"
    },
    "/_baselayout/contacts/": {
      "filePath": "_baselayout/contacts/index.tsx",
      "parent": "/_baselayout"
    },
    "/_baselayout/help/": {
      "filePath": "_baselayout/help/index.tsx",
      "parent": "/_baselayout"
    },
    "/_baselayout/settings/": {
      "filePath": "_baselayout/settings/index.tsx",
      "parent": "/_baselayout"
    },
    "/_baselayout/video/": {
      "filePath": "_baselayout/video/index.tsx",
      "parent": "/_baselayout"
    },
    "/$slug/folder/$folder/": {
      "filePath": "$slug/folder.$folder/index.tsx",
      "parent": "/$slug"
    },
    "/1219/admin/domain/": {
      "filePath": "1219/admin/domain/index.tsx"
    },
    "/1219/admin/login/": {
      "filePath": "1219/admin/login/index.tsx"
    },
    "/_baselayout/folder/$folder/": {
      "filePath": "_baselayout/folder/$folder/index.tsx",
      "parent": "/_baselayout"
    },
    "/1219/admin/domain/add/": {
      "filePath": "1219/admin/domain/add/index.tsx"
    },
    "/1219/admin/domain/edit/$domain/": {
      "filePath": "1219/admin/domain/edit.$domain/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
